all:
  children:
    db:
      hosts:
        dbserver:
          ansible_host: 192.168.56.102
    app:
      hosts:
        appserver:
          ansible_host: 192.168.56.101
    front:
      hosts:
        frontserver:
          ansible_host: 192.168.56.103
  vars:
    ansible_user: vagrant
