- name: Install PostgreSQL on dbserver
  hosts: db
  become: true

  vars:
    db_name: demo_db
    db_user: demo_user
    db_pass: demo_pass
    allowed_cidr: "192.168.56.0/24"

  tasks:
    - name: Install PostgreSQL + python driver
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Find postgresql.conf path
      shell: "ls /etc/postgresql/*/main/postgresql.conf | head -n 1"
      register: pg_conf
      changed_when: false

    - name: Find pg_hba.conf path
      shell: "ls /etc/postgresql/*/main/pg_hba.conf | head -n 1"
      register: pg_hba
      changed_when: false

    - name: Set listen_addresses = '*'
      lineinfile:
        path: "{{ pg_conf.stdout }}"
        regexp: "^#?listen_addresses\\s*=.*"
        line: "listen_addresses = '*'"
      notify: restart postgres

    - name: Allow connections from vagrant network
      lineinfile:
        path: "{{ pg_hba.stdout }}"
        line: "host    all             all             {{ allowed_cidr }}          md5"
        create: yes
      notify: restart postgres

    - name: Create DB user (psql) - idempotent
      shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}'" | grep -q 1 \
        || sudo -u postgres psql -c "CREATE ROLE {{ db_user }} LOGIN ENCRYPTED PASSWORD '{{ db_pass }}';"
      args:
        executable: /bin/bash

    - name: Create DB (psql) - idempotent
      shell: |
        sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'" | grep -q 1 \
        || sudo -u postgres createdb -O {{ db_user }} {{ db_name }}
      args:
        executable: /bin/bash


  handlers:
      - name: restart postgres
        service:
          name: postgresql
          state: restarted
