// Job DSL – defines ALL cloud pipelines

def repoUrl = 'https://github.com/it2022031/DevOps-2025.git'
def branch  = '*/main'

folder('cloud') {
    displayName('cloud')
    description('All cloud pipelines generated by seed job')
}

/* =========================
   Infra Ping Pipeline
   ========================= */
pipelineJob('cloud/infra-ping') {
    description('Ansible ping to all cloud infrastructure VMs')

    parameters {
        stringParam('LIMIT', 'all', 'Ansible limit (all / group / pattern)')
        booleanParam('VERBOSE', false, 'Enable ansible -vvv')
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote { url(repoUrl) }
                    branches(branch)
                }
            }
            scriptPath('ci/jenkins/jenkinsfiles/cloud_infra_ping.groovy')
            lightweight(true)
        }
    }
}

/*
ΑΡΓΟΤΕΡΑ ΕΔΩ:
pipelineJob('cloud/deploy-vms') { ... }
pipelineJob('cloud/deploy-docker') { ... }
pipelineJob('cloud/deploy-k8s') { ... }
*/
