// ci/jenkins/jobdsl/cloud_jobs.groovy
// This file is executed by the Job DSL plugin (seed job: "Process Job DSLs")

folder('cloud') {
    displayName('cloud')
    description('Cloud pipelines generated by Job DSL')
}

pipelineJob('cloud/ping-cloud-vms') {
    description('Ping cloud VMs using Ansible (created by Job DSL).')

    logRotator {
        numToKeep(30)
    }

    parameters {
        stringParam('BRANCH', 'main', 'Git branch to use')
        booleanParam('VERBOSE', false, 'Enable -vvv in ansible')
    }

    definition {
        cpsScm {
            scm {
                git {
                    remote {
                        url('https://github.com/it2022031/DevOps-2025.git')
                        // Αν έχεις credentials στο Jenkins, βάλε το ID εδώ:
                        // credentials('github-creds-id')
                    }
                    branch('$BRANCH')
                }
            }
            scriptPath('ci/jenkins/jenkinsfiles/cloud_ping.groovy')
            lightweight(true)
        }
    }
}
