---
- name: Install Java 21 on appserver
  hosts: app
  become: true

  tasks:
    - name: Install OpenJDK 21
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Show Java version
      debug:
        var: java_version.stderr_lines
