Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.boot_timeout = 600

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  def vb_defaults(vb)
    vb.memory = 2048
    vb.cpus = 2
  end

  INTNET_NAME = "dsnet"

  # -------- backend --------
  config.vm.define "backend" do |h|
    h.vm.hostname = "backend"

    h.vm.network "private_network",
      ip: "10.10.10.11",
      netmask: "255.255.255.0",
      virtualbox__intnet: INTNET_NAME

    # ✅ Port forward: Host (your PC) -> Guest (backend VM)
    # Open in browser/Postman on host: http://127.0.0.1:8088
    h.vm.network "forwarded_port", guest: 80, host: 8088, auto_correct: true

    h.vm.provider "virtualbox" do |vb|
      vb_defaults(vb)
    end
  end

  # -------- db --------
  config.vm.define "db" do |h|
    h.vm.hostname = "db"

    h.vm.network "private_network",
      ip: "10.10.10.12",
      netmask: "255.255.255.0",
      virtualbox__intnet: INTNET_NAME

    h.vm.provider "virtualbox" do |vb|
      vb_defaults(vb)
    end
  end

  # -------- front --------
  config.vm.define "front" do |h|
    h.vm.hostname = "front"

    h.vm.network "private_network",
      ip: "10.10.10.13",
      netmask: "255.255.255.0",
      virtualbox__intnet: INTNET_NAME

    h.vm.provider "virtualbox" do |vb|
      vb_defaults(vb)
    end
  end
end
